#!/usr/bin/python3
from tkinter import *
from termcolor import colored
import sys

try:
 ab = sys.argv[1]
except IndexError:
 print(colored("[!]","red"), "syntax : $ ./w.py file.txt")
else:
 root = Tk()
 root.configure(bg='black')
 root.title("- LOGGING TOOL - By m00nissmiling")
 root.geometry("600x700")
 f1 = Frame(root,bg='black')
 f1.pack(side=LEFT,padx=10)
 Label(f1,text='',bg='black',fg='red',width=30,font='Verdana 12 bold').pack(pady=25)
 Label(f1,text=' Issue Number ',bg='black',fg='red',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Title ',bg='black',fg='blue',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Project ',bg='black',fg='red',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Vuln Url ',bg='black',fg='blue',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Rate ',bg='black',fg='red',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Impact Detail ',bg='black',fg='blue',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Day ',bg='black',fg='green',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' SUN/MON/TUE ',bg='black',fg='green',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Month ',bg='black',fg='green',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Year ',bg='black',fg='green',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text=' Hour:Min [AM/PM] ',bg='black',fg='green',width=30,font='Verdana 12 bold').pack(pady=10)
 Label(f1,text='',bg='black',fg='yellow',width=30,font='Verdana 12 bold').pack(pady=10)
 f2 = Frame(root,bg='black')
 f2.pack(side=RIGHT)
 Label(f2,text='[-LOGGER-]',bg='black',fg='white',width=30,font='Verdana 20 bold').pack(pady=20)
 w1 = StringVar(root)
 en1 = Entry(f2,textvariable=w1,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='red',highlightcolor='white',width=150)
 en1.pack(pady=9)
 w2 = StringVar(root)
 en2 = Entry(f2,textvariable=w2,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='blue',highlightcolor='white',width=150)
 en2.pack(pady=9)
 w3 = StringVar(root)
 en3 = Entry(f2,textvariable=w3,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='red',highlightcolor='white',width=150)
 en3.pack(pady=9)
 w4 = StringVar(root)
 en4 = Entry(f2,textvariable=w4,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='blue',highlightcolor='white',width=150)
 en4.pack(pady=9)
 w40= StringVar(root)
 en40 = Entry(f2,textvariable=w40,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='red',highlightcolor='white',width=150)
 en40.pack(pady=9)
 w5= StringVar(root)
 en5 = Entry(f2,textvariable=w5,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='blue',highlightcolor='white',width=150)
 en5.pack(pady=9)
 w6= StringVar(root)
 en6 = Entry(f2,textvariable=w6,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='red',highlightcolor='white',width=150)
 en6.pack(pady=9)
 w7= StringVar(root)
 en7 = Entry(f2,textvariable=w7,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='green',highlightcolor='white',width=150)
 en7.pack(pady=9)
 w8= StringVar(root)
 en8 = Entry(f2,textvariable=w8,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='green',highlightcolor='white',width=150)
 en8.pack(pady=9)
 w9= StringVar(root)
 en9 = Entry(f2,textvariable=w9,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='green',highlightcolor='white',width=150)
 en9.pack(pady=8)
 w10= StringVar(root)
 en10 = Entry(f2,textvariable=w10,bg='black',fg='lime',borderwidth=2,highlightthickness=2,highlightbackground='green',highlightcolor='white',width=150)
 en10.pack(pady=8)
 def log():
  inp0 = w1.get()
  inp1 = w2.get()
  inp10 = w3.get()
  inp2 = w40.get()
  inp3 = w4.get()
  inp4 = w7.get()
  inp5 = w6.get()
  inp6 = w8.get()
  inp7 = w9.get()
  inp8 = w5.get()
  inp9 = w10.get()
  fileo = open(ab,"a")
  fileo.write(f"\n#issue{inp0}\nTitle - {inp1} < {inp10}\nVulnerable Url - {inp3}\nRate - {inp2}\nDetail - {inp8}\n[{inp4}] [{inp9}] [{inp5}/{inp6}/{inp7}]\n----------------------------")
  fileo.close()
  en1.delete(0,END)
  en2.delete(0,END) 
  en4.delete(0,END)
  en40.delete(0,END)
  en5.delete(0,END)
  en10.delete(0,END)
   
 Button(f2,text="ADD",fg='white',bg='red',command=log,width=20,borderwidth=2,relief="flat",activebackground="green",activeforeground="white",highlightthickness=2, highlightbackground="red",font='Verdana 10 bold').pack(pady=5)
 root.mainloop()
